<div id="patientEventDialog">
    
    <form class="user-input margin20 test">
       
    <div class="input-control select">
        <select>
            <option>Value 1</option>
            <option>Value 2</option>
            <option>Value 3</option>
        </select>
    </div>
        
        <div class="margin20"></div>

        <div class="form-actions">
            <button class="button success">Done</button>
            <button class="button" type="button" onclick="$.Dialog.close()">Cancel</button> 
        </div>
    </form>
</div>


