<div id="patientEventDialog">

    <form class="user-input margin20 test">

        <div class="details">

        </div>

        <div style="display: none" id="measurementField">
            <div class="margin20"></div>
            <label>Type measurement value in: <span class="unit"></span></label>
            <div class="input-control text">
                <input name="measurement" type="text" value="" placeholder="input patient login"/>
                <button class="btn-clear"></button>
            </div>

        </div>
        <div class="margin20"></div>
        <div class="form-actions">
            <button type="button" class="button success submit-event-state">Done</button>
            <button type="button" class="button" type="button" onclick="$.Dialog.close()">Cancel</button> 
        </div>


    </form>
</div>


