<div class="grid bg-lightGray">
    <div class="row">
        <div class="span4 offset4">
            <div class="grid margin20">

                <div class="row">
                    <h1>
                        <i class="icon-accessibility on-left"></i>
                        AAL
                    </h1> 
                    <h3>ambient assisted living </h3>
                </div>

                <div class="row"></div>

                <form action="auth/login" method="post">
                    <div class="row no-margin">
                        <label>Login:</label>
                        <div class="input-control text">
                            <input name="login" type="text" value="" placeholder="input login"/>
                            <button class="btn-clear"></button>
                        </div>
                    </div>

                    <div class="row no-margin">
                        <label>Password:</label>
                        <div class="input-control password">
                            <input name="password" type="password" value="" placeholder="input password"/>
                            <button class="btn-reveal"></button>
                        </div>
                    </div>

                    <div class="row centeredButton margin5">
                        <button class="info size2 large">Login</button>
                    </div>
                </form>

            </div>
        </div>
    </div>

</div>



