<div class="grid bg-lightGray">
   
    <div class="padding20 centerZiom">
        <div>
            <h1>
                <i class="icon-accessibility on-left"></i>
                AAL
            </h1> 
            <h3>ambient assisted living </h3>
        </div>

        <div class=""></div>

        <form action="auth/login" method="post">

            <div class=" no-margin">
                <label>Login:</label>
                <div class="input-control text">
                    <input name="login" type="text" value="" placeholder="input login"/>
                    <button class="btn-clear"></button>
                </div>
            </div>

            <div class=" no-margin">
                <label>Password:</label>
                <div class="input-control password">
                    <input name="password" type="password" value="" placeholder="input password"/>
                    <button class="btn-reveal"></button>
                </div>
            </div>

            <div class=" centeredButton margin5">
                <button class="info size2 large">Log in</button>
            </div>
        </form>

    </div>

</div>



