<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('IOSR')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ?>

        <!-- Styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->appendStylesheet($this->basePath() . '/css/iconFont.min.css')
                ->appendStylesheet($this->basePath() . '/css/metro-bootstrap.min.css')
                ->appendStylesheet($this->basePath() . '/css/metro-bootstrap-responsive.min.css')
		->appendStylesheet($this->basePath() . '/css/style.css')

        ;
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->appendFile($this->basePath() . '/js/lib/jquery-2.1.0.min.js')
                ->appendFile($this->basePath() . '/js/lib/jquery-ui-1.10.4.custom.min.js')
                ->appendFile($this->basePath() . '/js/lib/bootstrap.min.js')
                ->appendFile($this->basePath() . '/js/lib/metro.min.js')
                ->appendFile($this->basePath() . '/js/lib/metro-streamer.js')
                ->appendFile($this->basePath() . '/js/lib/jquery.widget.min.js')
                ->appendFile($this->basePath() . '/js/lib/jquery.mousewheel.js')
                ->appendFile($this->basePath() . '/js/lib/jquery.textarea-expander.js')
                ->appendFile($this->basePath() . '/js/lib/metro-datepicker.js')
                ->appendFile($this->basePath() . '/js/doc.js')
                ->appendFile($this->basePath() . '/js/schedule/initialSettings.js')
                ->appendFile($this->basePath() . '/js/schedule/patient/eventClick.js')
                ->appendFile($this->basePath() . '/js/schedule/doctor/eventClick.js')
                ->appendFile($this->basePath() . '/js/schedule/doctor/eventsSubmiting.js')
                ->appendFile($this->basePath() . '/js/schedule/streamerUpdater.js')
                ->appendFile($this->basePath('js/admin/adminDialogsRenderer.js'))
                ->appendFile($this->basePath('js/admin/rowsAndSelectsRenderer.js'))
                ->appendFile($this->basePath('js/admin/fillMeasurementsTable.js'))
                ->appendFile($this->basePath('js/admin/loadAdminData.js'))
                ->appendFile($this->basePath('js/admin/buttonsActions.js'))
                ->appendFile($this->basePath('js/layout/layout.js'))
        ;
        ?>

    </head>
    <body class="metro">
        <div id="wrap">
        <nav class="navigation-bar dark">
            <nav class="navigation-bar-content">
                <div class="element"> <i class='on-left icon-accessibility'></i>AAL FANCY NAME </div>

                <div class="element place-right">
                    <a class="dropdown-toggle" href="#">
                        <i class='on-left icon-cog'></i>
                    </a>
                    <ul class="dropdown-menu place-right" data-role="dropdown">
                        <li><a href="auth/logout">Log out</a></li>
                        <li><a href="#">Easter time</a></li>

                    </ul>
                </div>

                <span class="element-divider place-right"></span>

                <a class="element place-right" href="#" id="printPage"><span class="icon-printer"></span></a>
                <span class="element-divider place-right"></span>
                <?php
                    $children = $this->viewModel()->getCurrent()->getChildren();
                    $child = $children[0];
                ?>
                <button class="element place-right" data-id="<?=  $child->id; ?>" data-group="<?= $child->group ?>" id="credentials">
                    <?= $child->name; ?>
                </button>
            </nav>
        </nav>
        <?php echo $this->content; //print index.html ?>
        <?php
        echo $this->inlineScript()
            //->appendFile($this->basePath('js/hourPicker.js'))
            //->appendFile($this->basePath('js/plik2.js'))
            //->appendFile($this->basePath('js/plik3.js'))
        ;
        ?>
         </div>
    </body>
</html>
