<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('IOSR')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->appendStylesheet($this->basePath() . '/css/style.css')
                        ->appendStylesheet($this->basePath() . '/css/iconFont.min.css')
                        ->appendStylesheet($this->basePath() . '/css/metro-bootstrap.min.css')
                        ->appendStylesheet($this->basePath() . '/css/metro-bootstrap-responsive.min.css')
                     //   ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                     //   ->appendStylesheet($this->basePath() . '/css/bootstrap-timepicker.min.css')
						
	;?>

        <!-- Scripts -->
        <?php echo $this->headScript()
                        ->appendFile($this->basePath() . '/js/lib/jquery-2.1.0.min.js')
			->appendFile($this->basePath() . '/js/lib/jquery-ui-1.10.4.custom.min.js')
                     //  ->appendFile($this->basePath() . '/js/lib/bootstrap.min.js')			->appendFile($this->basePath() . '/js/lib/metro.min.js')
                     //  ->appendFile($this->basePath() . '/js/lib/bootstrap-timepicker.min.js')
                
             
                
        ; ?>

    </head>
    <body class="metro">
        <?php 
			echo $this->content; //print index.html
		?>
        <?php 
			echo $this->inlineScript()
				//->appendFile($this->basePath('js/hourPicker.js'))
				//->appendFile($this->basePath('js/plik2.js'))
				//->appendFile($this->basePath('js/plik3.js'))
			;
		?>
    </body>
</html>
