<div id='addDoctorForm'>
    <form class="user-input margin20 test">

        <label>Name:</label>
        <div class="input-control text">
            <input type="text" value="" placeholder="input doctor name"/>
            <button class="btn-clear"></button>
        </div>

        <label>Surname:</label>
        <div class="input-control text">
            <input type="text" value="" placeholder="input doctor surname"/>
            <button class="btn-clear"></button>
        </div>

        <label>E-mail:</label>
        <div class="input-control text">
            <input type="email" data-transform="input-control" placeholder="input doctor e-mail"/>
            <button class="btn-clear"></button>
        </div>

        <label>Select institution:</label>
        <div class="input-control select">
            <select>
                <option>Zofia Choralska</option>
                <option>Kamil Zaziebiony</option>
                <option>Pawel Połamany</option>
            </select>
        </div>

        <div class="margin20"></div>
        <div class="form-actions">
            <button class="button success">Add</button>
            <button class="button" type="button" onclick="$.Dialog.close()">Cancel</button> 
        </div>
    </form>

</div>