<div id="addInstitutionForm">
    
    <form class="user-input margin20 test" id="testForm">
       
        <label>Institution name:</label>
        <div class="input-control text">
            <input type="text" value="" placeholder="input institution name"/>
            <button class="btn-clear"></button>
        </div>
        
        <div class="margin20"></div>

        <div class="form-actions  centeredButton">
            <button class="button success" id="jsonTest">Add</button>
            <button class="button" type="button" onclick="$.Dialog.close()">Cancel</button> 
        </div>
    </form>
</div>


