<div id="addInstitutionForm">
    <form class="user-input margin20 test">

        <label>Institution name:</label>
        <div class="input-control text">
            <input name="name" type="text" value="" placeholder="input institution name"/>
            <button class="btn-clear"></button>
        </div>

        <div class="margin20"></div>

        <div class="form-actions centeredButton">
            <button type="button" class="button success" id="sumbit-add-institution-button">Add</button>
            <button type="button" class="button" onclick="$.Dialog.close()">Cancel</button> 
        </div>

    </form>
</div>


