<div id='addPatientForm'>

    <form class="user-input margin20 test">

        <label>Name:</label>
        <div class="input-control text">
            <input type="text" value="" placeholder="input patient name"/>
            <button class="btn-clear"></button>
        </div>

        <label>Surname:</label>
        <div class="input-control text">
            <input type="text" value="" placeholder="input patient surname"/>
            <button class="btn-clear"></button>
        </div>

        <label>E-mail:</label>
        <div class="input-control text">
            <input type="email" data-transform="input-control" placeholder="input patient e-mail"/>
            <button class="btn-clear"></button>
        </div>

        <label>Institution:</label>
        <div class="input-control select">
            <select class="fillWithInstitutions">
                <option disabled selected style='display: none'>
                    Select institution</option>
            </select>
        </div>

        <label>Select doctor:</label>
        <div class="input-control select">
            <select class="fillWithDoctors">
                <option disabled selected class="firstSelect">
                    Select doctor</option>
            </select>
        </div>

        <div class="margin20"></div>

        <div class="form-actions  centeredButton">
            <button class="button success">Add</button>
            <button class="button" type="button" onclick="$.Dialog.close()">Cancel</button> 
        </div>
    </form>

</div>