<div id='addPatientForm'>

    <form class="user-input margin20 test">

        <label>Login:</label>
        <div class="input-control text">
            <input name="login" type="text" value="" placeholder="input patient login"/>
            <button class="btn-clear"></button>
        </div>
        
        <label>Password:</label>
        <div class="input-control password">
            <input name="password" type="password" value="" placeholder="input password"/>
            <button class="btn-reveal"></button>
        </div>
        
        <label>Name:</label>
        <div class="input-control text">
            <input name="firstname" type="text" value="" placeholder="input patient name"/>
            <button class="btn-clear"></button>
        </div>

        <label>Surname:</label>
        <div class="input-control text">
            <input name="lastname" type="text" value="" placeholder="input patient surname"/>
            <button class="btn-clear"></button>
        </div>

        <label>E-mail:</label>
        <div class="input-control text">
            <input name="email" type="email" data-transform="input-control" placeholder="input patient e-mail"/>
            <button class="btn-clear"></button>
        </div>

        <label>Institution:</label>
        <div class="input-control select">
            <select name="institution" class="fillWithInstitutions">
                <option disabled selected style='display: none'>
                    Select institution</option>
            </select>
        </div>

        <label>Select doctor:</label>
        <div class="input-control select">
            <select name="doctor" class="fillWithDoctors">
                <option disabled selected class="firstSelect">
                    Select doctor</option>
            </select>
        </div>
       
        <input name="group" value="patient" style="display: none">

        <div class="margin20"></div>

        <div class="form-actions  centeredButton">
            <button class="button success" type="button" id="submit-add-patient">Add</button>
            <button class="button" type="button" onclick="$.Dialog.close()">Cancel</button> 
        </div>
    </form>

</div>