<div class="grid">
    <div class="row">

        <div class="span4">               

            <div class="input-control select">
                <select class="fillWithInstitutions">
                    <option disabled selected class="firstSelect">
                        Select institution</option>
                    <option>All institutions</option>
                </select>
            </div>


        </div>
    </div>

    <div class="row">

        <div class="tab-control" data-role="tab-control">
            <ul class="tabs">
                <li class="active"><a href="#_page_1">Doctors</a></li>
                <li><a href="#_page_2">Patients</a></li>
            </ul>

            <div class="frames">
                <div class="frame" id="_page_1">
                    <table class="table striped">
                        <thead>
                            <tr>
                                <th class="text-left">Name</th>
                                <th class="text-left">Surname</th>
                                <th class="text-left">Login</th>
                                <th class="text-left">E-mail</th>
                            </tr>
                        </thead>

                        <tbody class="fillWithDoctorsTable">
                        </tbody>

                    </table>
                </div>
                <div class="frame" id="_page_2">
                    <table class="table striped">
                        <thead>
                            <tr>
                                <th class="text-left">Name</th>
                                <th class="text-left">Surname</th>
                                <th class="text-left">Login</th>
                                <th class="text-left">E-mail</th>
                                <th class="text-left">Assigned doctor</th>
                            </tr>
                        </thead>

                        <tbody class="fillWithPatientsTable">
                        </tbody>

                    </table>
                </div>
            </div>
        </div>

    </div>

    <div class="row">
        <button class="large" id="addNewIstitutionButton">Add institution</button>  
        <button class="large" id="addNewDoctor">Add doctor</button>  
        <button class="large" id="addNewPatient">Add patient</button>  
    </div>
</div>

<div style="display: none">
    <?= $this->addInstitution ?>
    <?= $this->addDoctor ?>
    <?= $this->addPatient ?>
    <?= $this->createBinding ?>
</div>