<div id="patientEventDialog">
    
    <form class="user-input margin20 test">
       
        <div class="detailsDialog">
        </div>
        
        <div class="margin20"></div>

        <div class="form-actions">
            <button class="button success">Done</button>
            <button class="button" type="button" onclick="$.Dialog.close()">Cancel</button> 
        </div>
    </form>
</div>


