<div class="grid" style="display: none;">
    <div class="row">
        <div class="accordion" data-role="accordion">
            <div class="accordion-frame">
                <a href="#" class="heading">Measurements results</a>
                <div class="content">...</div>
            </div>
            <div class="accordion-frame">
                <a href="#" class="heading">Events management</a>
                <div class="content">

                   
                </div>
            </div>
        </div>
    </div>
</div>

<div class="grid">
    <div class="row">


        <div class="span3">               


            <?= $this->selectPatients ? $this->selectPatients : "" ?>

            <div id="datepicker" class="input-control text" data-role="datepicker"
                 data-format="dd/mm/yyyy"
                 data-position="bottom"
                 data-effect="slide"
                 >
                <input type="text" id="schedulerDate">
                <button class="btn-date"></button>
            </div>

        </div>
    </div>

    <div class="row">

        <?= $this->streamer ?>

    </div>

    <div style="display: none;">
        <?= $this->eventDialogs ?>
    </div>
</div>
