<div class="grid">
    <div class="row">
        <div class="accordion" data-role="accordion">
            <div class="accordion-frame">
                <a href="#" class="heading">Measurements results</a>
                <div class="content" style="display: block">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="text-left">Date</th>
                                <th class="text-left">Hour</th>
                                <th class="text-left">Patient</th>
                                <th class="text-left">Type</th>
                                <th class="text-left">Value</th>
                            </tr>
                        </thead>

                        <tbody id="measurementsTable">

                        </tbody>

                        <tfoot></tfoot>
                    </table>
                </div>
            </div>

            <div class="accordion-frame">
                <a href="#" class="heading">Undone activities</a>
                <div class="content" style="display: block">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="text-left">Date</th>
                                <th class="text-left">Hour</th>
                                <th class="text-left">Patient</th>
                                <th class="text-left">Type</th>
                                <th class="text-left">Title</th>
                            </tr>
                        </thead>

                        <tbody id="undone-activities-table">

                        </tbody>

                        <tfoot></tfoot>
                    </table>
                </div>
            </div>

            <div class="accordion-frame">
                <a href="#" class="heading">Events management</a>
                <div class="content" style="display: block">

                    <div class="span3 no-margin">               


                        <?= $this->selectPatients ? $this->selectPatients : "" ?>

                        <div id="datepicker" class="input-control text" data-role="datepicker"
                             data-format="dd/mm/yyyy"
                             data-position="bottom"
                             data-effect="slide"
                             data-date="<?php echo date("Y-m-d"); ?>"
                             >
                            <input type="text" id="schedulerDate">
                            <button class="btn-date"></button>
                        </div>

                    </div>
                    <?= $this->streamer ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div style="display: none;">
    <?= $this->eventDialogs ?>
</div>

