

<div class="grid">
    <div class="row">

        <div class="span3">               


            <?= $this->selectPatients ? $this->selectPatients : "" ?>

            <div id="datepicker" class="input-control text" data-role="datepicker"
                 data-date="05/05/2014"
                 data-format="dd/mm/yyyy"
                 data-position="bottom"
                 data-effect="slide"
                 >
                <input type="text" id="schedulerDate">
                <button class="btn-date"></button>
            </div>

        </div>
    </div>

    <div class="row">

        <?= $this->streamer ?>

    </div>

    <div style="display: none;">
        <?= $this->eventDialogs ?>
    </div>
</div>
