

<div class="grid">
    <div class="row">

        <div class="span3">               


            <div class="input-control select">
                <select class="fillWithPatients">
                    <option disabled selected style='display: none'>Select your patient</option>
                </select>
            </div>

            <div class="input-control text" data-role="datepicker"
                 data-date="01/01/2014"
                 data-format="dd/mm/yyyy"
                 data-position="bottom"
                 data-effect="slide">
                <input type="text">
                <button class="btn-date"></button>
            </div>

        </div>
    </div>

    <div class="row">

        <?= $this->streamer ?>

    </div>

    <div style="display: none;">
        <?= $this->eventDialogs ?>
    </div>
</div>
