<div id="patientEventDialog">
    
    <form class="user-input margin20 test">
       
        <div>
            Lorem ipsum dolor sit amet, consectetur 
            adipisicing elit, sed do eiusmod tempor 
            incididunt ut labore et dolore magna aliqua.
            Ut enim ad minim veniam, quis nostrud exercitation
            ullamco laboris nisi ut aliquip ex ea commodo 
            consequat. Duis aute irure dolor in reprehenderit
            in voluptate velit esse cillum dolore eu fugiat 
            nulla pariatur. Excepteur sint occaecat cupidatat
            non proident, sunt in culpa qui officia deserunt 
            mollit anim id est laborum.
        </div>
        
        <div class="margin20"></div>

        <div class="form-actions">
            <button class="button success">Done</button>
            <button class="button" type="button" onclick="$.Dialog.close()">Cancel</button> 
        </div>
    </form>
</div>


