<div class="streamer" data-role="streamer" data-scroll-bar="true" data-slide-to-group="3" data-slide-speed="500">
    <div class="streams">
        <div class="streams-title">
            <div>
                TODAY'S ACTIVITIES
            </div>
        </div>
        <div class="stream bg-teal">
            <div class="stream-title">DIET</div>
        </div>
        <div class="stream bg-orange">
            <div class="stream-title">EXERCISES</div>
        </div>
        <div class="stream bg-pink">
            <div class="stream-title">MEDICINES</div>
        </div>
        <div class="stream bg-darkGreen">
            <div class="stream-title">DOCTOR'S VISITS</div>
        </div>
    </div>

    <div class="events" style="overflow-x: scroll">
        <div class="events-area" style="width: 4900px; height: 335px">

            <div class="events-grid">

                <div class="event-group">
                    <div class="event-stream" >
                        <div class="event"></div>
                        <div class="event double padding10 ribbed-teal">
                            <div>9:20 - 10:00</div>
                            <h2 class="no-margin">Breakfast</h2>
                            <div class="detailsStreamer" style="display: none">
                                brum
                            </div>
                        </div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event triple padding10 bg-teal">
                            <div>11:40 - 12:40</div>
                            <h2 class="no-margin">Dinner</h2>
                        </div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                    </div>

                    <div class="event-stream" >

                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event triple padding10 bg-orange">
                            <div>10:00 - 11:00</div>
                            <h2 class="no-margin">Morning Exercises</h2>
                        </div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>

                    </div>

                    <div class="event-stream" >
                        <div class="event padding10 ribbed-pink">
                            <div>9:00 - 9:20</div>
                            <h2 class="no-margin">Medicines 1</h2>
                        </div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event padding10 bg-pink">
                            <div>9:00 - 9:20</div>
                            <h2 class="no-margin">Medicines 2</h2>
                        </div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>

                    </div>

                    <div class="event-stream" >
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div> 
                        <div class="event"></div>
                        <div class="event padding10 bg-darkGreen quadro">
                            <div>9:00 - 9:20</div>
                            <h2 class="no-margin">dr. Lol visit</h2>
                        </div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div>
                        <div class="event"></div> 

                    </div>


                </div>

            </div>
        </div>
    </div>
</div>