<h1>Data model and database interfaces</h1>

<script type="text/javascript">
    var user = {
        name: "User",
        fields: [
            {name:"id.$id", type:"string"},
            {name:"login", type:"string"},
            {name:"password", type:"string"},
            {name:"group", type:"string"},
        ],
        interfaces: [
            {
                name: "Add user",
                url: "/db/user/add",
                parameters: [
                    {name:"login", type:"string"},
                    {name:"password", type:"string"},
                    {name:"group", type:"string"},
                    {name:"firstname", type:"string"},
                    {name:"lastname", type:"string"},
                    {name:"email", type:"string"},
                    {name:"institution", type:"string (id)", optional: true},
                    {name:"doctor", type:"string (id)", optional: true},
                ],
            },
        ],
    };
    generateDocs(user);
    
    var institution = {
        name: "Institution",
        fields: [
            {name:"id.$id", type:"string"},
            {name:"name", type:"string"},
        ],
        interfaces: [
            {
                name: "Get institution",
                url: "/db/institution",
                parameters: [
                    {name:"id", type:"string"},
                ],
            },
            {
                name: "Get all institutions",
                url: "/db/institution/all",
                example: "$.ajax('/db/institution/all').success(function(data) { alert(JSON.stringify(data)); });",
            },
            {
                name: "Add institution",
                url: "/db/institution/add",
                example: '$.ajax({ type: "POST", url: "db/institution/add", data: { "name": "Placowka gicior" }});',
                parameters: [
                    {name:"name", type:"string"},
                ],
            }
        ],
    };
    generateDocs(institution);
    
    var doctor = {
        name: "Doctor",
        fields: [
            {name:"id.$id", type:"string"},
            {name:"firstname", type:"string"},
            {name:"lastname", type:"string"},
            {name:"user", type:"string (id)"},
            {name:"institution", type:"string (id)"},
        ],
        interfaces: [
            {
                name: "Get doctor",
                url: "/db/doctor",
                parameters: [
                    {name:"id", type:"string"},
                ],
            },
            {
                name: "Get all doctors",
                url: "/db/doctor/all",
                example: '$.ajax("/db/doctor/all").success(function(data) { alert(JSON.stringify(data)); });',
            },
        ],
    };
    generateDocs(doctor);
    
    var patient = {
        name: "Patient",
        fields: [
            {name:"id.$id", type:"string"},
            {name:"firstname", type:"string"},
            {name:"lastname", type:"string"},
            {name:"schedule", type:"Schedule"},
            {name:"user", type:"string (id)"},
            {name:"institution", type:"string (id)"},
            {name:"doctor", type:"string (id)"},
        ],
        interfaces: [
            {
                name: "Get patient",
                url: "/db/patient",
                parameters: [
                    {name:"id", type:"string"},
                ],
            },
            {
                name: "Get all patients",
                url: "/db/patient/all",
                example: '$.ajax("/db/patient/all").success(function(data) { alert(JSON.stringify(data)); });',
            },
        ],
    };
    generateDocs(patient);
    
    var schedule = {
        name: "Schedule",
        fields: [
            {name:"days", type:"Day[]"},
        ],
    };
    generateDocs(schedule);
    
    var day = {
        name: "Day",
        fields: [
            {name:"date", type:"string"},
            {name:"streams", type:"Stream[]"},
        ],
    };
    generateDocs(day);
    
    var stream = {
        name: "Stream",
        fields: [
            {name:"activity", type:"string"},
            {name:"events", type:"Event[]"},
        ],
    };
    generateDocs(stream);
    
    var event = {
        name: "Event",
        fields: [
            {name:"title", type:"string"},
            {name:"details", type:"string"},
            {name:"time", type:"string"},
            {name:"duration", type:"integer"},
            {name:"state", type:"string"},
        ],
        interfaces: [
            {
                name: "Add event",
                url: "/db/event/add",
                parameters: [
                    {name:"patientid", type:"string"},
                    {name:"date", type:"string"},
                    {name:"activity", type:"string"},
                    {name:"title", type:"string"},
                    {name:"details", type:"string"},
                    {name:"time", type:"string"},
                    {name:"duration", type:"integer"},
                    {name:"state", type:"string"},
                ],
            },
        ],
    };
    generateDocs(event);
    
</script>
