<div id="content">
    <!--a href="<?= $this->url('home') ?>">
        <div class="tile bg-darkPink">
            <div class="tile-content icon">
                <i class="icon-sun-3"></i>
            </div>
            <div class="tile-status">
                <span class="name">
    <?= $this->zmienna ?>
                </span>
            </div>
        </div>
    </a> -->

    <nav class="navigation-bar dark">
        <nav class="navigation-bar-content">
            <div class="element"> <i class='on-left icon-accessibility'></i>AAL FANCY NAME </div>

            <div class="element place-right">
                <a class="dropdown-toggle" href="#">
                    <i class='on-left icon-cog'></i>
                </a>
                <ul class="dropdown-menu place-right" data-role="dropdown">
                    <li><a href="#">Log out</a></li>
                    <li><a href="#">Change password</a></li>

                </ul>
            </div>

            <span class="element-divider place-right"></span>

            <a class="element place-right" href="#"><span class="icon-printer"></span></a>
            <span class="element-divider place-right"></span>
            <button class="element place-right">
                Andrian Leczniczy
            </button>
        </nav>
    </nav>

    <div class="grid">
        <div class="row">

            <div class="span3">               


                <div class="input-control select">
                    <select>
                        <option disabled selected style='display: none'>Select your patient</option>
                        <option>Zofia Choralska</option>
                        <option>Kamil Zaziebiony</option>
                        <option>Pawel Polamany</option>
                    </select>
                </div>

                <div class="input-control text" data-role="datepicker"
                     data-date="01/01/2014"
                     data-format="dd/mm/yyyy"
                     data-position="bottom"
                     data-effect="slide">
                    <input type="text">
                    <button class="btn-date"></button>
                </div>

            </div>
        </div>

        <div class="row">


            <div class="streamer" data-role="streamer" data-scroll-bar="true" data-slide-to-group="3" data-slide-speed="500">
                <div class="streams">
                    <div class="streams-title">
                        <div>
                            TODAY'S ACTIVITIES
                        </div>
                    </div>
                    <div class="stream bg-teal">
                        <div class="stream-title">DIET</div>
                    </div>
                    <div class="stream bg-orange">
                        <div class="stream-title">EXERCISES</div>
                    </div>
                    <div class="stream bg-pink">
                        <div class="stream-title">MEDICINES</div>
                    </div>
                    <div class="stream bg-darkGreen">
                        <div class="stream-title">DOCTOR'S VISITS</div>
                    </div>
                </div>

                <div class="events" style="overflow-x: scroll">
                    <div class="events-area" style="width: 4900px; height: 335px">

                        <div class="events-grid">

                            <div class="event-group">
                                <div class="event-stream" >
                                    <div class="event"></div>
                                    <div class="event double padding10 ribbed-teal">
                                        <div>9:20 - 10:00</div>
                                        <h2 class="no-margin">Breakfast</h2>
                                    </div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event triple padding10 bg-teal">
                                        <div>11:40 - 12:40</div>
                                        <h2 class="no-margin">Dinner</h2>
                                    </div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                </div>

                                <div class="event-stream" >

                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event triple padding10 bg-orange">
                                        <div>10:00 - 11:00</div>
                                        <h2 class="no-margin">Morning Exercises</h2>
                                    </div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>

                                </div>

                                <div class="event-stream" >
                                    <div class="event padding10 ribbed-pink">
                                        <div>9:00 - 9:20</div>
                                        <h2 class="no-margin">Medicines 1</h2>
                                    </div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event padding10 bg-lightBlue">
                                        <div>9:00 - 9:20</div>
                                        <h2 class="no-margin">Medicines 2</h2>
                                    </div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>

                                </div>

                                <div class="event-stream" >
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div> 
                                    <div class="event"></div>
                                    <div class="event padding10 bg-darkGreen quadro">
                                        <div>9:00 - 9:20</div>
                                        <h2 class="no-margin">dr. Lol visit</h2>
                                    </div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div>
                                    <div class="event"></div> 

                                </div>


                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <button class="large">Add activity</button>  
        </div>
    </div>

    <div class="window flat shadow span7">
        <div class="caption">
            <span class="icon icon-sun"></span> 
            <div class="title">New activitity for Zofia Choralska</div>
            <button class="btn-close"></button>
        </div>
        <div class="content">
            <form>
                <div class="grid margin20">

                    <div class="row no-margin"> 
                        <div class="span2">Activity type: </div>
                        <div class="span4">
                            <div class="input-control select">
                                <select>
                                    <option disabled selected style='display: none;'>Select activity type</option>
                                    <option>Diet</option>
                                    <option>Exercise</option>
                                    <option>Medicines</option>
                                    <option>Doctor's visit</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row no-margin">
                        <div class="span2">Title: </div>
                        <div class="span4">
                            <div class="input-control text" data-role="input-control">
                                <input type="text" placeholder="Type activity title...">
                                <button class="btn-clear" tabindex="-1" type="button"></button>
                            </div>
                        </div>
                    </div>

                    <div class="row no-margin">
                        <div class="span2">Detailed info: </div>
                        <div class="span4">
                            <div class="input-control textarea">
                                <textarea></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="row no-margin">
                        <div class="span1">Begin time: </div>
                        <div class="span1 offset1">
                            <div class="input-control select">
                                <select>
                                    <option>06</option>
                                    <option>07</option>                                    <option>00</option>
                                    <option>08</option>                   <option>00</option>
                                    <option>09</option>
                                    <option>10</option>
                                    <option>11</option>                                    <option>00</option>
                                    <option>12</option>                   <option>00</option>
                                    <option>13</option>
                                    <option>14</option>                   <option>00</option>
                                    <option>15</option>
                                    <option>16</option>                   <option>00</option>
                                    <option>17</option>
                                    <option>18</option>                   <option>00</option>
                                    <option>19</option>
                                    <option>20</option>                   <option>00</option>
                                    <option>21</option>
                                    <option>22</option>                   <option>00</option>
                                    <option>23</option>  
                                </select>
                            </div>
                        </div>
                        <div class="span1">
                            <div class="input-control select">
                                <select>
                                    <option>00</option>
                                    <option>20</option>
                                    <option>40</option>
                                </select>
                            </div>
                        </div>

                    </div>

                    <div class="row no-margin">
                        <div class="span2"> Duration: </div>
                        <div class="span4">
                            <div class="input-control select">
                                <select>
                                    <option disabled selected style='display: none'>Select activity duration time</option>
                                    <option>20 min</option>
                                    <option>40 min</option>
                                    <option>1 h</option>
                                    <option>1 h 20 min</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="offset2">
                            <button>Cancel</button>
                            <button class="success">OK</button>
                        </div>
                    </div>

                </div>
        </div>
    </div>
</div>


