<div id="content">

    <div class="window flat shadow span7">
        <div class="caption">
            <span class="icon icon-sun"></span> 
            <div class="title">New activitity for Zofia Choralska</div>
            <button class="btn-close"></button>
        </div>
        <div class="content">
            <form>
                <div class="grid margin20">

                    <div class="row no-margin"> 
                        <div class="span2">Activity type: </div>
                        <div class="span4">
                            <div class="input-control select">
                                <select>
                                    <option disabled selected style='display: none;'>Select activity type</option>
                                    <option>Diet</option>
                                    <option>Exercise</option>
                                    <option>Medicines</option>
                                    <option>Doctor's visit</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row no-margin">
                        <div class="span2">Title: </div>
                        <div class="span4">
                            <div class="input-control text" data-role="input-control">
                                <input type="text" placeholder="Type activity title...">
                                <button class="btn-clear" tabindex="-1" type="button"></button>
                            </div>
                        </div>
                    </div>

                    <div class="row no-margin">
                        <div class="span2">Detailed info: </div>
                        <div class="span4">
                            <div class="input-control textarea">
                                <textarea></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="row no-margin">
                        <div class="span1">Begin time: </div>
                        <div class="span1 offset1">
                            <div class="input-control select">
                                <select>
                                    <option>06</option>
                                    <option>07</option>                                 
                                    <option>08</option>  
                                    <option>09</option>
                                    <option>10</option>
                                    <option>11</option>
                                    <option>12</option>
                                    <option>13</option>
                                    <option>14</option>
                                    <option>15</option>
                                    <option>16</option>
                                    <option>17</option>
                                    <option>18</option>
                                    <option>19</option>
                                    <option>20</option>
                                    <option>21</option>
                                    <option>22</option>
                                    <option>23</option> 
                                </select>
                            </div>
                        </div>
                        <div class="span1">
                            <div class="input-control select">
                                <select>
                                    <option>00</option>
                                    <option>20</option>
                                    <option>40</option>
                                </select>
                            </div>
                        </div>

                    </div>

                    <div class="row no-margin">
                        <div class="span2"> Duration: </div>
                        <div class="span4">
                            <div class="input-control select">
                                <select>
                                    <option disabled selected style='display: none'>Select activity duration time</option>
                                    <option>20 min</option>
                                    <option>40 min</option>
                                    <option>1 h</option>
                                    <option>1 h 20 min</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="offset2">
                            <button>Cancel</button>
                            <button class="success">OK</button>
                        </div>
                    </div>

                </div>
        </div>
    </div>
</div>


